### ISSUE TITLE
net.mamoe.mirai包下存在类找不到

### ISSUE THREAD

**Issue by msyCandy** [Erzbir/Mirai-NumeronBot#2]
![image](https://user-images.githubusercontent.com/30425236/228499027-1015877d-bf2f-484e-8415-0b820fcb6b88.png)
如图，项目拉下来后，代码中有部分类找不到，尝试升级mirai-core-jvm到最新（2.15.0-M1）也不行。

求助，应该怎么改

**Comment by Erzbir** [comment]
切换到master分支看看

**Comment by Erzbir** [comment]
切换过去之后，点右边的maven，然后刷新

**Comment by Erzbir** [comment]
修复了

**Comment by Erzbir** [comment]
稍等, 我把创建文件的那块代码修一下
